version: '3'
services:
  bot:
    build: ./bot
    environment:
      - NODE_ENV=development
    volumes:
      - ./bot:/usr/src/bot
      - /usr/src/bot/node_modules 
    ports:
      - 3000:2222
    tty: true